### ISSUE TITLE
[Suggestion] Ensure compatibility with RustPython

### ISSUE THREAD

**Issue by FoxNerdSaysMoo** [GrandMoff100/Jolly#1]
This project would benefit if it is compatible with [RustPython](https://rustpython.github.io), as this would allow for script linking similar to JS.

**Comment by GrandMoff100** [comment]
Could you elaborate on what ways Jolly should support RustPython?

**Comment by FoxNerdSaysMoo** [comment]
Avoid C bindings, and try to keep files in memory

**Comment by FoxNerdSaysMoo** [comment]
Requesting makes this very difficult, going to close this until rustpython has a better requests system for wasm
